### PR TITLE
Whitespace ignoring option

### PR DESCRIPTION
**Pull request by carloscz**

### CODE REVIEW

**Comment by carloscz** [comment]
@alessioalex bump :)

**Comment by alessioalex** [comment]
hey there, sorry for the delay. @carloscz can you modify the pull request to include `args` instead of `arr`. I think you made a typo. Thank you for the pull request.

**Comment by carloscz** [comment]
@alessioalex yeah, sorry, it should be OK now :)

**Comment by alessioalex** [comment]
published `1.1.0` to npm, tnx again

**Pull request merged**
